export default {
  CREATED: 'CREATED',
  ADDED_PROOF_OF_PAYMENT_FULL: 'ADDED_PROOF_OF_PAYMENT_FULL',
  APPROVED_PROOF_OF_PAYMENT_FULL: 'APPROVED_PROOF_OF_PAYMENT_FULL',
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED',
  IS_ABLE_TO_BUILT: 'IS_ABLE_TO_BUILT',
  IS_UNABLE_TO_BUILT: 'IS_UNABLE_TO_BUILT',
  ADDED_PROOF_OF_PAYMENT_DEPOSIT: 'ADDED_PROOF_OF_PAYMENT_DEPOSIT',
  APPROVED_PROOF_OF_PAYMENT_DEPOSIT: 'APPROVED_PROOF_OF_PAYMENT_DEPOSIT',
  BUILT_COMPLETE: 'BUILT_COMPLETE',
}
