export default {
  CREATED: 'CREATED',
  ADDED_PROOF_OF_PAYMENT_FULL: 'ADDED_PROOF_OF_PAYMENT_FULL',
  APPROVED_PROOF_OF_PAYMENT_FULL: 'APPROVED_PROOF_OF_PAYMENT_FULL',
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED',
}
